version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=test-spark-cluster
    volumes:
      - data:/hadoop/dfs/name
      - ./conf/nn-hdfs-site.xml:/opt/hadoop-3.2.1/etc/hadoop/hdfs-site.xml
      - ./conf/core-site.xml:/opt/hadoop-3.2.1/etc/hadoop/core-site.xml
    ports:
      - "9870:9870"
    networks:
      - bigdata

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - ./data:/hadoop/dfs/data
      - ./conf/dn-hdfs-site.xml:/opt/hadoop-3.2.1/etc/hadoop/hdfs-site.xml
      - ./conf/core-site.xml:/opt/hadoop-3.2.1/etc/hadoop/core-site.xml
    networks:
      - bigdata

  hive:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    depends_on:
      - namenode
    environment:
      HIVE_ROOT_ENV: 1
    volumes:
      - ./conf/hive-hdfs-site.xml:/opt/hadoop-2.7.4/etc/hadoop/hdfs-site.xml
      - ./conf/core-site.xml:/opt/hadoop-2.7.4/etc/hadoop/core-site.xml
    ports:
      - "10000:10000"
    networks:
      - bigdata

  hbase:
    image: harisekhon/hbase:2.1
    container_name: hbase
    depends_on:
      - namenode
      - datanode
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    ports:
      - "16010:16010"  # HBase Master UI
      - "2181:2181"    # Zookeeper
    networks:
      - bigdata

  pig:
    build:
      context: ./pig
    container_name: pig
    depends_on:
      - namenode
      - hive
    networks:
      - bigdata

volumes:
  data:

networks:
  bigdata:
    driver: bridge
